# Generated by Django 4.2.13 on 2026-08-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('actividad', models.CharField(choices=[('cine', 'Cine'), ('gokart', 'Go Kart'), ('boliche', 'Boliche'), ('feria', 'Feria / juegos mecánicos')], max_length=20)),
                ('restaurante', models.CharField(choices=[('mcdonalds', "McDonald's"), ('pizza', 'Pizza'), ('parrilla', 'Parrilla / Asados'), ('sushi', 'Sushi')], max_length=20)),
                ('respondio_si', models.BooleanField(default=True)),
                ('correo_enviado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuestas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
