# Generated by Django 4.2.13 on 2026-08-31 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propuesta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuesta',
            name='celular',
        ),
    ]
